server:
  port: 8080

spring:
  application:
    name: yu-mall-gateway-service
  cloud:
    nacos:
      server-addr: 192.168.100.128:8848
      username: nacos
      password: nacos
      config:
        namespace: yu-mall
        group: DEFAULT_GROUP
        import-check:
          enabled: false
      discovery:
        server-addr: 192.168.100.128:8848
        namespace: yu-mall
        group: DEFAULT_GROUP
        fail-fast: false
  config:
    import:
      - optional:nacos:shared-log.yaml?group=DEFAULT_GROUP&refreshEnabled=true
      - optional:nacos:gateway-routes.json?group=DEFAULT_GROUP&refreshEnabled=true

knife4j:
  enable: true
  gateway:
    enabled: true
    enable-openapi: true
    routes:
      - name: User Service
        service-name: user-center-service
        path: /user/**
        url: /v3/api-docs
      - name: Order Service
        service-name: order-service
        path: /order/**
        url: /v3/api-docs
      - name: Admin Service
        service-name: yu-mall-admin-service
        path: /admin/**
        url: /v3/api-docs

yu:
  jwt:
    location: classpath:hmall.jks
    password: hmall123
    alias: hmall
  auth:
    excludePaths:
      - /search/**
      - /users/login
      - /items/**
      - /shops/**
      - /users/register
      - /users/captcha/**
      - /upload
      - /comments/all/**
      - /admins/**