server:
  port: 8082

spring:
  application:
    name: yu-mall-product-service
  autoconfigure:
    exclude:
      - com.baomidou.mybatisplus.autoconfigure.DdlAutoConfiguration
  cloud:
    nacos:
      server-addr: 192.168.100.128:8848
      username: nacos
      password: nacos
      config:
        namespace: yu-mall
        group: DEFAULT_GROUP
        import-check:
          enabled: false
      discovery:
        server-addr: 192.168.100.128:8848
        namespace: yu-mall
        group: DEFAULT_GROUP
        fail-fast: false
  config:
    import:
      - optional:nacos:shared-jdbc.yaml?group=DEFAULT_GROUP&refreshEnabled=true
      - optional:nacos:shared-log.yaml?group=DEFAULT_GROUP&refreshEnabled=true
      - optional:nacos:shared-seata.yaml?group=DEFAULT_GROUP&refreshEnabled=true
      - optional:nacos:shared-sentinel.yaml?group=DEFAULT_GROUP&refreshEnabled=true
      - optional:nacos:shared-feign.yaml?group=DEFAULT_GROUP&refreshEnabled=true
      - optional:nacos:shared-mq.yaml?group=DEFAULT_GROUP&refreshEnabled=true
  data:
    redis:
      database: 0
      password:
      connect-timeout: 200ms
      sentinel:
        master: yu-mall-master
        nodes: 192.168.100.128:27001,192.168.100.128:27002,192.168.100.128:27003
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto

jackson:
  date-format: yyyy-MM-dd HH:mm:ss
  time-zone: GMT+8
  deserialization:
    fail-on-unknown-properties: false

yu:
  db:
    host: 192.168.100.128
    port: 3307
    database: mall-item
    un: root
    pw: 123