spring:
  rabbitmq:
    host: 192.168.100.128
    port: 5672
    virtual-host: /yu
    username: YU
    password: 123
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      message-converter: org.springframework.amqp.support.converter.Jackson2JsonMessageConverter
    listener:
      simple:
        prefetch: 5
        acknowledge-mode: auto
        retry:
          enabled: true
          initial-interval: 1000ms
          multiplier: 2
          max-attempts: 3
          stateless: true
        message-converter: org.springframework.amqp.support.converter.Jackson2JsonMessageConverter