seata:
  registry:
    type: nacos
    nacos:
      server-addr: 192.168.100.128:8848
      namespace: public
      group: DEFAULT_GROUP
      application: seata-server
      username: nacos
      password: nacos
  tx-service-group: mall
  service:
    vgroup-mapping:
      mall: "default"
  data-source-proxy-mode: AT