server:
  port: 8092

spring:
  application:
    name: yu-mall-ai-service
  cloud:
    nacos:
      server-addr: 192.168.100.128:8848
      config:
        server-addr: 192.168.100.128:8848
        import-check:
          enabled: false
      discovery:
        server-addr: 192.168.100.128:8848
  ai:
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      api-key: ${ALI_API_KEY}
      chat:
        options:
          model: qwen3.5-plus
          temperature: 0.1

#yu:
#  ai:
#    default-model: ${YU_AI_MODEL:gpt-4o-mini}
#    default-temperature: ${YU_AI_TEMPERATURE:0.7}
#    system-prompt: ${YU_AI_SYSTEM_PROMPT:You are a helpful assistant.}

logging:
  level:
    com.yu: debug
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: logs/${spring.application.name}
