server:
  port: 8086

spring:
  application:
    name: yu-mall-pay-service
  cloud:
    nacos:
      server-addr: 192.168.100.128:8848
      username: nacos
      password: nacos
      config:
        namespace: yu-mall
        group: DEFAULT_GROUP
        import-check:
          enabled: false
      discovery:
        server-addr: 192.168.100.128:8848
        namespace: yu-mall
        group: DEFAULT_GROUP
        fail-fast: false
  config:
    import:
      - optional:nacos:shared-jdbc.yaml?group=DEFAULT_GROUP&refreshEnabled=true
      - optional:nacos:shared-log.yaml?group=DEFAULT_GROUP&refreshEnabled=true
      - optional:nacos:shared-seata.yaml?group=DEFAULT_GROUP&refreshEnabled=true
      - optional:nacos:shared-sentinel.yaml?group=DEFAULT_GROUP&refreshEnabled=true
      - optional:nacos:shared-feign.yaml?group=DEFAULT_GROUP&refreshEnabled=true
      - optional:nacos:shared-mq.yaml?group=DEFAULT_GROUP&refreshEnabled=true
      - optional:nacos:pay-service.yaml?group=DEFAULT_GROUP&refreshEnabled=true
